### ISSUE TITLE
Newest Intel Wifi kext file problem

### ISSUE THREAD

**Issue by PPPPPH** [adityabakare/macOS-Dell-Latitude-E7470#25]
looks like the current AirportItlwm.kext has been updated in your recently update to opencore 0.66,but I reinstall the whole macos and WiFi is still not usable. check the md5 and find out the file is not official AirportItlwm_v1.2.0_stable nor latest debug 1.3.0 .
Copy the official AirportItlwm_v1.2.0_stable fix the WiFi.
BTW,If I want to add nvmefix.kext,all I need to do is paste nvmefix.kext into exist EFI/OC/kext folder and run propertree,select config.plist and make a OC snapshot,is that correct?

**Comment by adityabakare** [comment]
WiFi works fine with the one I've included. I've use the debug alpha which was built up to [this commit](https://github.com/OpenIntelWireless/itlwm/commit/ecf78fcf28b985df1a7d669a3f2e558ff7ada3af). You might have checked the md5 with the newer alpha. 
And yes, for adding NVMeFix, the method that you've mentioned is correct. I haven't included it because I don't have an NVMe SSD.

Converting this to a Discussion.
