### ISSUE TITLE
Google Chrome freezes the whole computer when playing videos

### ISSUE THREAD

**Issue by AlienKevin** [adityabakare/macOS-Dell-Latitude-E7470#7]
## Problems
On Google Chrome, there have been several times when web videos suddenly freeze for a second or two before resuming.

Disable hardware acceleration in the settings of Google Chrome **does not** solve this issue. I suspect there are issues with the driver for the integrated graphics card but I don't have enough expertise to look into it. In the meantime, I would recommend not doing anything graphics intensive until there's a fix.

**Comment by adityabakare** [comment]
I had this too once in a while, on Big Sur only. A restart usually fixes this. But I suspect the problem is with WEG kext( some stuff including DRM for GPUs seems to be broken on Big Sur(basically most of the userspace implementation)). I'll update the kexts when Acidanthera releases new ones, and then let's see if it's fixed.

**Comment by adityabakare** [comment]
This seems to have fixed on latest OpenCore Update with latest WEG kext. Still, I'll wait for a confirmation.

**Comment by AlienKevin** [comment]
I can confirm that video streaming is smooth now. Thanks for keeping up with the OC updates!
